language: node_js
node_js:
    - "node"

# Code coverage report
dist: trusty
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build -t lcov -p /home/travis/build/GMartigny/pencil.js/.cache/jest-webpack/ -d --exit-code $TRAVIS_TEST_RESULT

# Lerna install
before_install:
    - npm i lerna
install:
    - npm run init
