language: node_js
node_js:
    - "node"

# Code coverage report
dist: trusty
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_script:
    - ./cc-test-reporter format-coverage -t lcov
    - ./cc-test-reporter upload-coverage

# Lerna install
install:
    - npx lerna bootstrap --hoist
